<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Html2x.Diagnostics.Contracts\Html2x.Diagnostics.Contracts.csproj" />
    <ProjectReference Include="..\..\Html2x.Diagnostics\Html2x.Diagnostics.csproj" />
    <ProjectReference Include="..\..\Html2x.LayoutEngine.Contracts\Html2x.LayoutEngine.Contracts.csproj" />
    <ProjectReference Include="..\..\Html2x.LayoutEngine.Fragments\Html2x.LayoutEngine.Fragments.csproj" />
    <ProjectReference Include="..\..\Html2x.LayoutEngine.Geometry\Html2x.LayoutEngine.Geometry.csproj" />
    <ProjectReference Include="..\..\Html2x.LayoutEngine.Pagination\Html2x.LayoutEngine.Pagination.csproj" />
    <ProjectReference Include="..\..\Html2x.LayoutEngine.Stage.Contracts\Html2x.LayoutEngine.Stage.Contracts.csproj" />
    <ProjectReference Include="..\..\Html2x.LayoutEngine.Style\Html2x.LayoutEngine.Style.csproj" />
    <ProjectReference Include="..\..\Html2x.LayoutEngine\Html2x.LayoutEngine.csproj" />
    <ProjectReference Include="..\..\Html2x.RenderModel\Html2x.RenderModel.csproj" />
    <ProjectReference Include="..\..\Html2x.Renderers.Pdf\Html2x.Renderers.Pdf.csproj" />
    <ProjectReference Include="..\..\Html2x.Resources\Html2x.Resources.csproj" />
    <ProjectReference Include="..\..\Html2x.Text\Html2x.Text.csproj" />
    <ProjectReference Include="..\..\Html2x\Html2x.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
